/* This file is autogenerated, do not edit*/
#include "OpenSkyPlanetarium-static_automoc.dir/moc_LaserDev_JM7QW6FHOODHNL.cpp"
#include "OpenSkyPlanetarium-static_automoc.dir/moc_OpenSkyPlaneta_XXAPASN4WJY75T.cpp"
#include "OpenSkyPlanetarium-static_automoc.dir/moc_SerialCom_6526J7443TK2ZU.cpp"
#include "OpenSkyPlanetarium-static_automoc.dir/moc_OSPMainDialog_MZUIV64COS5K6N.cpp"
